FROM node:20-alpine

RUN apk add --no-cache postgresql-client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .
COPY .env.development .env

RUN npx prisma generate
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"] 